/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'StateAuditJob': CronHandler<{ topic: 'notification'; data: { template_id: string; email: string; template_data: Record<string, unknown> } }>
    'ProcessFoodOrder': EventHandler<{ email: string; quantity: unknown; pet_id: string }, { topic: 'notification'; data: { template_id: string; email: string; template_data: Record<string, unknown> } }>
    'Notification': EventHandler<{ template_id: string; email: string; template_data: Record<string, unknown> }, never>
    'ApiTrigger': ApiRouteHandler<{ pet: unknown; foodOrder?: unknown | unknown }, ApiResponse<200, { id: string; name: string; photoUrl: string }>, { topic: 'process-food-order'; data: { email: string; quantity: unknown; pet_id: string } }>
    'GenerateReportAPI': ApiRouteHandler<{ session_id: string }, ApiResponse<200, { status: string; session_id: string; report_id: string; message: string; requires_approval: boolean }>, never>
    'ApproveReportAPI': ApiRouteHandler<{ session_id: string; report_id: string; approved: boolean; reviewer_name: string; reviewer_comments?: string | unknown; edited_report?: Record<string, unknown> | unknown }, ApiResponse<200, { status: string; session_id: string; report_id: string; pdf_path?: string | unknown; message: string }>, never>
    'LabAnalysisAPI': ApiRouteHandler<{ session_id: string; lab_data: Record<string, number> }, ApiResponse<200, { status: string; session_id: string; message: string; abnormal_count: unknown; critical_count: unknown }>, never>
    'ImageAnalysisAPI': ApiRouteHandler<{ patient_id: string; patient_name: string; age: string; gender: string; study_date: string; image_type: string; image_path: string }, ApiResponse<200, { status: string; session_id: string; patient_id: string; message: string }>, never>
    'GetReportAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { status: string; session_id: string; report?: Record<string, unknown> | unknown; pdf_path?: string | unknown }>, never>
    'DownloadPDFAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, unknown> | ApiResponse<404, { status: string; message: string; report_id?: string | unknown; file_available?: boolean }>, never>
  }
    
}